version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8003:8000"
    volumes:
      - ./backend:/app
    environment:
      - ENV=dev
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - app-network

  frontend:
    image: node:20-slim
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8083:5173"
    command: sh -c "npm install --legacy-peer-deps && npm run dev -- --host"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

