version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8003:8000"
    volumes:
      - ./backend:/app
    environment:
      - ENV=dev
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "8083:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

